# Main navigation.
nav:
  - Introduction: index.md
  - Team: team.md
  - Funding: funding.md
  - Credits: credits.md
  - License: license.md
  - Contact: contact.md
  - User Guide:
      - Einleitung: user-guide/index.md
      # - Setting up: user-guide/setup.md
      - Navigation: user-guide/navigate.md
      - Dateien hinzufügen:
          - Enleitung: user-guide/library/import-vs-index.md
          - Indexieren: user-guide/library/indexing.md
          - Importieren: user-guide/library/import.md
          - Upload über die App: user-guide/library/upload.md
          - WebDAV Upload: user-guide/library/webdav.md
          - Originale: user-guide/library/files.md
        #- Import from camera: user-guide.md
        #- Import from Facebook: user-guide.md
        #- Import from NAS: user-guide.md
        #- Import from Apple Photos: user-guide.md
        #- Import from One Drive: user-guide.md
      # - Sync and Back Up:
      # - WebDAV Sync
      #    - Nextcloud: user-guide/nextcloud.md
      - Organisation:
          - Entdecken:
            - Bereiche: user-guide/organize/browse.md
            - Ansicht: user-guide/organize/views.md
            - Suche & Filter: user-guide/organize/search.md
          #- Search Filter: user-guide/organize/search.md
          - Review: user-guide/organize/review.md
          - Stacks: user-guide/organize/stacks.md
          - Panoramas: user-guide/organize/panoramas.md
          - Scans: user-guide/organize/scans.md
          - Private: user-guide/organize/private.md
          - Archive: user-guide/organize/archive.md
          - Albums: user-guide/organize/albums.md
          - Folders: user-guide/organize/folders.md
          - Labels: user-guide/organize/labels.md
          - Places: user-guide/organize/places.md
          - Videos: user-guide/organize/video.md
          - Moments: user-guide/organize/moments.md
          - Calendar: user-guide/organize/calendar.md
          - Download photos: user-guide/organize/download.md
          - Edit photos: user-guide/organize/edit.md
      - Backup:
          - Connect via WebDAV:  user-guide/backup/webdav.md
          - Nextcloud Sync:  user-guide/backup/nextcloud.md
      - Share:
          - Share album via link: user-guide/share/share.md
      - Settings:
          - Library: user-guide/settings/library.md
          - User Interface: user-guide/settings/ui.md
          - Account: user-guide/settings/account.md
          - Places: user-guide/settings/places.md
          - Thumbnails: user-guide/settings/thumbnails.md
      - Use Cases:
          - Export files from Google Photos: user-guide/use-cases/google.md
          - Export files from Flickr: user-guide/use-cases/flickr.md
          #- Link directories from remote:
      - FAQ: user-guide/faq.md
    # - Metadata: user-guide/metadata.md

# External links.
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/photoprism
    - icon: fontawesome/brands/paypal
      link: https://www.paypal.me/photoprism
    - icon: material/chat
      link: https://gitter.im/browseyourlife/community
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/browseyourlife
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/photoprism/
    - icon: material/home
      link: https://photoprism.org/

# Project paths.
docs_dir: docs
site_dir: site

# Project information.
site_name: PhotoPrism
site_description: User Guide - German
site_author: PhotoPrism.org
site_url: https://docs.photoprism.org/de

# Repository information.
repo_name: photoprism/photoprism
repo_url: https://github.com/photoprism/photoprism
edit_uri: ""
copyright: 'Made with ❤ in Berlin'

# Theme configuration.
theme:
  name: 'material'
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: de
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: white
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: img/favicon-16.png

plugins:
  - search

# MkDocs extensions.
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
